### ISSUE TITLE
Training code - FPR95

### ISSUE THREAD

**Issue by ngunsu** [szagoruyko/cvpr15deepcompare#12]
I think you need to add fprev = L[i] to 
 
```
    if L[i] > fprev then
      x:resize(j)
      y:resize(j)
      x[j] = FP/N
      y[j] = TP/P
      j = j + 1
    end
```

Cheers

**Comment by szagoruyko** [comment]
thanks. it was a very old code, I just pushed a better version https://github.com/szagoruyko/cvpr15deepcompare/commit/ad1f85e86c2be49160c2bd7bac739ab2a72a909d
