### ISSUE TITLE
Interpreting Network Outputs

### ISSUE THREAD

**Issue by Supersak80** [szagoruyko/cvpr15deepcompare#13]
Hi @szagoruyko , when I run test patches through a trained network, how am I to interpret the output similarity scores? It doesn't appear that they are normalized to [0,1].

**Comment by Supersak80** [comment]
@szagoruyko Sergey, your input is greatly appreciated with the question above.

**Comment by szagoruyko** [comment]
@Supersak80 sorry, I forgot to answer. the outputs are not normalized to [0,1], higher the score - more similar patches are.

**Comment by Supersak80** [comment]
@szagoruyko Thank you, Sergey!
