### ISSUE TITLE
Additional Training Network Architectures

### ISSUE THREAD

**Issue by Supersak80** [szagoruyko/cvpr15deepcompare#15]
@szagoruyko Hi Sergey, would you be able to release the additional training models that you discussed in your paper? Specifically, the 2ch2stream and the 2 channel deep? I appreciate it!

**Comment by Supersak80** [comment]
@szagoruyko Sergey, thank you for your time and help with all of this. If you could also release the siamese SPP training model, that would be quite helpful!

**Comment by szagoruyko** [comment]
@Supersak80 added via https://github.com/szagoruyko/cvpr15deepcompare/commit/bb6f35c51f5361600f6a17947bbcb8f2068a8198, I trained the models in the new code to check that they produce the same results. There is no difference in SPP training, see the paper.
