### ISSUE TITLE
Problem when loading 2chdeep pre-trained models

### ISSUE THREAD

**Issue by abursuc** [szagoruyko/cvpr15deepcompare#17]
Hi, 
I'm trying to load your already trained models using the 2chdeep setup. There seems to be a problem with the way you saved them.
This is the error I get when doing torch.load(): 
```
unknown Torch class <inn.SpatialMaxPooling>
```

Could you please check the exported models?

Thanks a lot.

**Comment by szagoruyko** [comment]
do `luarocks install inn` and before loading the network `require 'inn'`. this is an old module that was integrated into nn.

**Comment by abursuc** [comment]
Thanks for the help. I should have explored a bit further the matter. I just wanted to use and off the shelf model quickly for a task.
Nice work, by the way!
