### ISSUE TITLE
unable to download models (nn format or binary format)

### ISSUE THREAD

**Issue by Andy0731** [szagoruyko/cvpr15deepcompare#19]
@szagoruyko Hi, I'm very interested in your work. But I'm unable to download your models (nn format or binary format). Did you remove them?

**Comment by szagoruyko** [comment]
That's because Dropbox updated their rules for sharing `Public` folders. I uploaded all models in this tar file: <https://www.dropbox.com/s/7l2912lrlptyyaz/cvpr2015matching_networks.tar.gz?dl=0>

**Comment by Andy0731** [comment]
@szagoruyko Copy that! Thank you so much!

**Comment by szagoruyko** [comment]
fixed the links in readme.
