### ISSUE TITLE
Unable to download patch data

### ISSUE THREAD

**Issue by handworker** [szagoruyko/cvpr15deepcompare#20]
Hi, Dr. szagoruyko, your data link 'http://www.cs.ubc.ca/~mbrown/patchdata/patchdata.html' is not work, there is a 404 error. Can you upload your data to a new website? I am interested with your work. Thanks!

**Comment by szagoruyko** [comment]
@handworker the original dataset webpage seems to be down, but I believe you can download the data from these mirrors:
<http://www.iis.ee.ic.ac.uk/~vbalnt/phototourism-patches/notredame.zip>
<http://www.iis.ee.ic.ac.uk/~vbalnt/phototourism-patches/yosemite.zip>
<http://www.iis.ee.ic.ac.uk/~vbalnt/phototourism-patches/liberty.zip>

**Comment by WongChen** [comment]
Hi, there,
I just want to know what  the numbers in the ***.txt** files included in the dataset means?


such as :

info.txt
0 0
0 0
1 0
1 0
...


m50_1000_1000_0.txt

55990 19870 0 55991 19870 0 0
222535 81100 0 434451 155431 0 0
27906 9967 0 27908 9967 0 0
313261 113021 0 313264 113021 0 0
361984 129234 0 413696 148086 0 0
.....

and other .txt files

**Comment by szagoruyko** [comment]
@WongChen you can take a look at this script: https://gist.github.com/szagoruyko/569c2b713a2c40629ecbe75fb3c9d980
`m50_1000_1000_0.txt` has information about matching/nonmatching pairs
`info.txt` is a list of all points as far as I remember

**Comment by WongChen** [comment]
@szagoruyko I get it.  
Thx a lot.

**Comment by szagoruyko** [comment]
added the mirrors to readme.

**Comment by sunbin1205** [comment]
@WongChen  Do you understand how the files in the dataset are arranged?
Do you make your own dataset in the same format?
Can you share some experience with me?
thank you very much!
