### ISSUE TITLE
Can't run cvpr2015 paper code

### ISSUE THREAD

**Issue by nazib** [szagoruyko/cvpr15deepcompare#21]
Hi @szagoruyko  I tried to run your code using torch. First I ran the code for torch format data creation. Then I tried to run the code in /training/train.lua but its fails all the time making error message about models.utils not found. Could you please update your readme with clear process of training and testing in torch?

I will be waiting for a favorable reply.
regards
Nazib

**Comment by szagoruyko** [comment]
@nazib from which folder do you run the script, does `models/utils.lua` exist there? what is the exact error you're getting?

**Comment by nazib** [comment]
Hi @szagoruyko, yes the models/utils.lua exist in the dierectory. First I created a bash file named 'train.sh' with following command:

export train_set=/media/nazib/Data/DeepNet_exp/Paper_patch/Data/notredame/data.t7
export test_set=/media/nazib/Data/DeepNet_exp/Paper_patch/Data/liberty/data.t7
export model=/media/nazib/Data/DeepNet_exp/Paper_patch/training/models/
export save_folder=logs/deepcompare_${model}_$RANDOM$RANDOM
mkdir -p $save_folder
th /media/nazib/Data/DeepNet_exp/Paper_patch/training/train.lua | tee $save_folder/log.txt

after that I tried to run the bash file from terminal, and it gives error message.

**Comment by nazib** [comment]
![image](https://cloud.githubusercontent.com/assets/14937060/25309493/28aabc7a-2812-11e7-9ff8-984072cde95f.png)

**Comment by szagoruyko** [comment]
@nazib the problem is that there's no `models/utils.lua` and other files in the folder you're calling the script from. Do `th train.lua` as specified in readme, and it will work.

**Comment by nazib** [comment]
Hi @szagoruyko code is running now. The problem was the bash file. However thanks for response.

**Comment by sunbin1205** [comment]
hi,The problem was the bash file. what is your mean?I met same error as you,can you tell me how to solve it??thanks
