### ISSUE TITLE
PyTorch evaluation dataset

### ISSUE THREAD

**Issue by system123** [szagoruyko/cvpr15deepcompare#23]
Hi,

I have downloaded the dataset and unzipped it into a folder. However, when I run the pytorch evaluation code it complains that 'liberty' is a folder. It appears that it is being loaded with load_lua. What format is the dataset expected to be in?

I also downloaded the t7 version of the liberty dataset from www.iis.ee.ic.ac.uk/~vbalnt/liberty-t7.tar.gz however, the code then crashes with the following error:

'''
parsed options: {'model': '2ch', 'lua_model': '../networks/2ch/2ch_liberty.t7', 'nthread': 4, 'gpu_id': '0', 'batch_size': 256, 'test_set': 'liberty.t7', 'test_matches': 'm50_100000_100000_0.txt'}
Loading test data
Traceback (most recent call last):
  File "eval.py", line 242, in <module>
    main()
  File "eval.py", line 176, in main
    test_iter = get_iterator(load_provider(), opt.batch_size, opt.nthread)
  File "eval.py", line 172, in load_provider
    p[t] = p[1][opt.test_matches][t]
KeyError: 1
'''

**Comment by szagoruyko** [comment]
@system123 the t7 version is different from mine. I added the script for preprocessing without lua, just numpy and opencv.
