### ISSUE TITLE
Can't download these links

### ISSUE THREAD

**Issue by ronyad** [szagoruyko/cvpr15deepcompare#26]
Looks like these links are broken
http://www.cs.ubc.ca/~mbrown/patchdata/liberty.zip
http://www.cs.ubc.ca/~mbrown/patchdata/notredame.zip
http://www.cs.ubc.ca/~mbrown/patchdata/yosemite.zip

Also all links on the script run_test.sh is broken

**Comment by litingfeng** [comment]
me too

**Comment by litingfeng** [comment]
Seems like code in run_test.sh is trying to download models first. You can try downloading manually [https://www.dropbox.com/s/7l2912lrlptyyaz/cvpr2015matching_networks.tar.gz?dl=0](https://www.dropbox.com/s/7l2912lrlptyyaz/cvpr2015matching_networks.tar.gz?dl=0). But I failed in this way too. And the links to download data doesn't work for me as well.

**Comment by litingfeng** [comment]
I find these datasets here:
[http://icvl.ee.ic.ac.uk/vbalnt/notredame.zip](http://icvl.ee.ic.ac.uk/vbalnt/notredame.zip)
[http://icvl.ee.ic.ac.uk/vbalnt/yosemite.zip](http://icvl.ee.ic.ac.uk/vbalnt/yosemite.zip)
[http://icvl.ee.ic.ac.uk/vbalnt/liberty.zip](http://icvl.ee.ic.ac.uk/vbalnt/liberty.zip)

However, I'm not sure they are exactly the same with that of this repo.

**Comment by szagoruyko** [comment]
@litingfeng check if you are behind firewall, https://www.dropbox.com/s/7l2912lrlptyyaz/cvpr2015matching_networks.tar.gz?dl=0 works. As for the data, it should be the same, I think.

**Comment by WifiSpy** [comment]
I cant get connected to dropbox's website because it was baned by our country, can you please provide other download source?

**Comment by szagoruyko** [comment]
see #29
