### ISSUE TITLE
pytorch/eval.py: where is the 'lua_model'

### ISSUE THREAD

**Issue by cathybgyz** [szagoruyko/cvpr15deepcompare#38]
I am trying to run the pytorch/eval.py, but I don't know which file I should put for required field '--lua_model'
I tried different lua files in training and torch folder, but always get this error: 

> torch.utils.serialization.read_lua_file.T7ReaderException: unknown type id 1970365810. The file may be corrupted.

Thank you for your help

**Comment by cathybgyz** [comment]
Found --Lua_model.

**Comment by sunbin1205** [comment]
I have the same problem as you. How do you solve it?
Thank you very much!
