### ISSUE TITLE
test_data.bin

### ISSUE THREAD

**Issue by DaddyWesker** [szagoruyko/cvpr15deepcompare#40]
Hi. 

I'm trying to run C++ API. After long-long suffering i've managed to compile torch and this. But there are one problem. When i'm trying to load test_data.bin using wget https://dl.dropboxusercontent.com/u/44617616/test_data.bin it says that "HTTP request sent, awaiting response... 404 Not Found". So, file is deleted from dropbox? Where could i find it?

Thanks in advance

**Comment by szagoruyko** [comment]
sorry, dropbox blocked the access, uploaded here: https://cvpr15deepcompare.s3-eu-west-1.amazonaws.com/test_data.bin
