### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by foelin** [szagoruyko/cvpr15deepcompare#6]
Hi, will you release your original training code in torch? Thanks

**Comment by szagoruyko** [comment]
@foelin yes, I had to rewrite the old code and testing the new one now.

**Comment by Supersak80** [comment]
@szagoruyko Hi Sergey, this was an excellent paper. Any updates on releasing the training code in Torch?

**Comment by szagoruyko** [comment]
@Supersak80 unfortunately the new code that I wrote still needs testing, will hopefully fix it soon.

**Comment by szagoruyko** [comment]
@foelin @Supersak80 training code is available now.
