### ISSUE TITLE
Generating new .bin files from existing .t7 models

### ISSUE THREAD

**Issue by mdaiter** [szagoruyko/cvpr15deepcompare#7]
How do you generate new .bin files from existing .t7 files?

For example: let's say I have a model I've self-trained or a model from a different project saved as a .t7 . Can I use your loading mechanism to load it in C++, and if so, how?

Thanks!

**Comment by szagoruyko** [comment]
Check https://github.com/mvitez/thnets and http://docs.opencv.org/3.1.0/d6/d0f/group__dnn.html#gsc.tab=0

**Comment by mdaiter** [comment]
Thanks!
