### ISSUE TITLE
Error building: ReLU.cu(13)

### ISSUE THREAD

**Issue by meder411** [szagoruyko/cvpr15deepcompare#9]
Evidently `THCudaTensor_pointwiseApply1` ought to be changed to `THC_pointwiseApply1` in cunnproduction/ReLU.cu(13). See [here](https://github.com/torch/cunn/pull/296/files). It built successfully for me after making that change.

**Comment by szagoruyko** [comment]
@meder411 I updated cunnproduction to use THCUNN library which now has no dependencies on lua.

**Comment by szagoruyko** [comment]
fixed via https://github.com/szagoruyko/cvpr15deepcompare/pull/10
